# Generated by Django 6.0.3 on 2026-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0002_remove_user_pin_user_password_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
